In [ ]:
import pandas as pd
import numpy as np



df = pd.read_csv(open('AQI_Data.csv'))

a. First 5 rows

In [72]:
df.head(8)

,City,Date,AQI,PM2.5,PM10,NO2,CO,O3,SO2
0,Delhi,2024-01-01,152,153,151,26.509131,1.581413,123.401530,25.062474
1,Delhi,2024-01-02,264,288,268,87.955853,1.242119,144.533790,5.926302
2,Delhi,2024-01-03,307,344,357,94.469744,0.101480,198.520196,32.786668
3,Delhi,2024-01-04,363,334,347,12.075618,1.097072,85.973585,7.099955
4,Delhi,2024-01-05,237,266,250,51.046299,1.591834,47.938019,28.140550
5,Delhi,2024-01-06,369,321,327,64.679037,0.423996,22.359803,47.699849
6,Delhi,2024-01-07,365,328,347,44.687485,0.130336,53.869827,15.846146
7,Delhi,2024-01-08,493,513,526,54.565922,0.165338,182.770876,16.645099

b. Last 5 rows

In [ ]:
df.tail(8)

,City,Date,AQI,PM2.5,PM10,NO2,CO,O3,SO2
2554,Pune,2024-12-24,368,332,357,49.869238,0.674453,197.461357,17.239430
2555,Pune,2024-12-25,168,187,198,58.462838,0.377190,115.077190,34.192485
2556,Pune,2024-12-26,80,95,82,88.809636,0.497454,129.043801,8.657624
2557,Pune,2024-12-27,419,448,462,26.701714,1.553582,86.973954,44.263423
2558,Pune,2024-12-28,252,202,182,19.920962,1.599821,41.939484,20.545087
2559,Pune,2024-12-29,365,414,410,80.815702,1.919950,39.982167,22.646297
2560,Pune,2024-12-30,253,269,285,66.231614,0.611800,63.966705,10.580135
2561,Pune,2024-12-31,95,140,117,99.505459,0.122817,112.774765,30.814997

c. Show dtypes and no. of non-null values

In [99]:
pd.DataFrame({'dtype': df.dtypes, 'non-null': df.notnull().sum()})

         dtype  non-null
City    object      2562
Date    object      2562
AQI      int64      2562
PM2.5    int64      2562
PM10     int64      2562
NO2    float64      2562
CO     float64      2562
O3     float64      2562
SO2    float64      2562

Print Mean AQI, Max PM2.5, Min PM10 for each city (using numpy)

In [63]:
for i in df.City.unique():
    print(i)
    print('Mean AQI: \t', np.mean(df[df.City == i].AQI))
    print('Max PM2.5: \t', np.max(df[df.City == i]['PM2.5']))
    print('Min PM10: \t', np.min(df[df.City == i].PM10))

Delhi
Mean AQI: 	 279.1530054644809
Max PM2.5: 	 539
Min PM10: 	 -17
Mumbai
Mean AQI: 	 287.7978142076503
Max PM2.5: 	 519
Min PM10: 	 20
Kolkata
Mean AQI: 	 265.9016393442623
Max PM2.5: 	 535
Min PM10: 	 -8
Chennai
Mean AQI: 	 274.3142076502732
Max PM2.5: 	 530
Min PM10: 	 -26
Bangalore
Mean AQI: 	 279.54371584699453
Max PM2.5: 	 527
Min PM10: 	 -1
Hyderabad
Mean AQI: 	 280.3551912568306
Max PM2.5: 	 543
Min PM10: 	 15
Pune
Mean AQI: 	 276.379781420765
Max PM2.5: 	 532
Min PM10: 	 6

Group the df by City and find

    avg AQI
    max PM2.5
    min PM10

display as dictionary

In [95]:
ans = df.groupby('City').agg({'AQI': 'mean', 'PM2.5': 'max', 'PM10': 'min'})
ans

                  AQI  PM2.5  PM10
City
Bangalore  279.543716    527    -1
Chennai    274.314208    530   -26
Delhi      279.153005    539   -17
Hyderabad  280.355191    543    15
Kolkata    265.901639    535    -8
Mumbai     287.797814    519    20
Pune       276.379781    532     6

In [96]:
ans = ans.to_dict(orient='index')
ans

{'Bangalore': {'AQI': 279.54371584699453, 'PM2.5': 527, 'PM10': -1},
 'Chennai': {'AQI': 274.3142076502732, 'PM2.5': 530, 'PM10': -26},
 'Delhi': {'AQI': 279.1530054644809, 'PM2.5': 539, 'PM10': -17},
 'Hyderabad': {'AQI': 280.3551912568306, 'PM2.5': 543, 'PM10': 15},
 'Kolkata': {'AQI': 265.9016393442623, 'PM2.5': 535, 'PM10': -8},
 'Mumbai': {'AQI': 287.7978142076503, 'PM2.5': 519, 'PM10': 20},
 'Pune': {'AQI': 276.379781420765, 'PM2.5': 532, 'PM10': 6}}

In [97]:
ans = {k: [*v.values()] for k, v in ans.items()}
ans

{'Bangalore': [279.54371584699453, 527, -1],
 'Chennai': [274.3142076502732, 530, -26],
 'Delhi': [279.1530054644809, 539, -17],
 'Hyderabad': [280.3551912568306, 543, 15],
 'Kolkata': [265.9016393442623, 535, -8],
 'Mumbai': [287.7978142076503, 519, 20],
 'Pune': [276.379781420765, 532, 6]}